export const navlinks=[
    {
        id:1,
        title:"Home",
        Link:"/"
    },
    {
        id:2,
        title:"About",
        Link:"/about"
    },
    {
        id:3,
        title:"Categories",
        Link:"/categories"
    },
    {
        id:4,
        title:"Contact",
        Link:"/contact"
    },
];